[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
teleology = "HpUrEiEnyqKHmhF5daMWygXKjZPPWgtnLMEvi13ZqBPu"

[programs.devnet]
teleology = "HpUrEiEnyqKHmhF5daMWygXKjZPPWgtnLMEvi13ZqBPu"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
